version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/JeremyAnsel.ColorQuant" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  GITHUB_TOKEN:
    secure: awbDbCVBldNyz+7VzGnSLlBnczS0NtXrUaS7UkrwoOoUIAzE70QHYfKQuTyOJavb

nuget:
  disable_publish_on_pr: true

before_build:
- nuget install EWSoftware.SHFB -Version 2015.10.10 -o JeremyAnsel.ColorQuant\packages\
- nuget install EWSoftware.SHFB.NETFramework -Version 4.6.0 -o JeremyAnsel.ColorQuant\packages\
- nuget restore JeremyAnsel.ColorQuant\JeremyAnsel.ColorQuant.sln

build:
  project: JeremyAnsel.ColorQuant\JeremyAnsel.ColorQuant.sln
  publish_nuget: true
  verbosity: minimal

after_build:
- if not defined APPVEYOR_PULL_REQUEST_NUMBER 7z a JeremyAnsel.ColorQuant.Documentation.zip .\JeremyAnsel.ColorQuant\Documentation\build\* > nul
- if not defined APPVEYOR_PULL_REQUEST_NUMBER appveyor PushArtifact JeremyAnsel.ColorQuant.Documentation.zip

test_script:
- JeremyAnsel.ColorQuant\run-tests.cmd

deploy:
- provider: NuGet
  api_key:
    secure: 8B7BSDgsTQqRD0xPzQjGcUFHitr2KvJHpFUlZQIPIcj4la6FAVxUzfj+7FVsb4o/
  skip_symbols: true
  on:
    branch: master
    DEPLOY: True

after_deploy:
- if "%DEPLOY%" == "True" git clone -q --branch=gh-pages --depth 5 git://github.com/JeremyAnsel/JeremyAnsel.ColorQuant.git gh-pages
- if "%DEPLOY%" == "True" cd gh-pages
- if "%DEPLOY%" == "True" git checkout -qf gh-pages
- if "%DEPLOY%" == "True" git config core.safecrlf false
- if "%DEPLOY%" == "True" git config push.default simple
- "if \"%DEPLOY%\" == \"True\" git config user.name \"Jérémy Ansel\""
- if "%DEPLOY%" == "True" git config user.email JeremyAnsel@users.noreply.github.com
- if "%DEPLOY%" == "True" if exist doc rd /s /q doc
- if "%DEPLOY%" == "True" md doc
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\JeremyAnsel.ColorQuant\Documentation\build doc
- if "%DEPLOY%" == "True" git add --all doc > nul
- if "%DEPLOY%" == "True" git commit -m "Update doc generated by CI"
- if "%DEPLOY%" == "True" if exist coverage rd /s /q coverage
- if "%DEPLOY%" == "True" md coverage
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\JeremyAnsel.ColorQuant\build\coverage coverage
- if "%DEPLOY%" == "True" git add --all coverage > nul
- if "%DEPLOY%" == "True" git commit -m "Update code coverage generated by CI"
- if "%DEPLOY%" == "True" git push -q https://%GITHUB_TOKEN%@github.com/JeremyAnsel/JeremyAnsel.ColorQuant.git
